all:
	g++ search_currency.cpp -std=c++11 -o hw2
kuo:
	g++ kuo.cpp -std=c++11 -o kuo -O2
submit:
	g++ submit-hw2.cpp -std=c++11 -o sub-hw2 -O2

stl:
	g++ stl-sub-hw2.cpp -std=c++11 -o stl-hw2 -O2
stdin:
	g++ stdin_search_currency.cpp -std=c++11 -o stdin-hw2 -O2
test:
	g++ test_search_currency.cpp -std=c++11 -o test-hw2
unit:	
	g++ unit_test.cpp -std=c++11 -o unit_test
final:	
	g++ final-hw2.cpp -std=c++11 -o final -O2
prac:	
	g++ hw2_practice.cpp -std=c++11 -o prac -O2
